### ISSUE TITLE
Add option to publish diagram configuration from Shiny

### ISSUE THREAD

**Issue by itsdani** [FTSRG/mondo-sam#2]
It would be great to export (and maybe import) the diagram configuration from Shiny so that users don't have to modify all the required settings on each startup.

**Comment by istvanrath** [comment]
+1

**Comment by zkovari** [comment]
Yes, indeed, that's the plan, I try to accomplish it in a few days. Thanks.

**Comment by zkovari** [comment]
It became possible to export the configurations from Shiny to a JSON file. Actually, this configuration can be reused by the other reporting script as well, thus, the whole plot generation process can be done automatically. I updated the [reporting page](https://github.com/FTSRG/mondo-sam/wiki/Reporting) with the extended configuration, so I think that [#5](https://github.com/FTSRG/mondo-sam/issues/5) is solved too.

**Comment by abelhegedus** [comment]
Thanks!
