### ISSUE TITLE
Location does not exist on Publish page

### ISSUE THREAD

**Issue by itsdani** [FTSRG/mondo-sam#3]
I cannot publish images from Shiny. There is always a "Location does not exist" message under the `Save diagrams` button. It seems that this occurs with both relative and absolute file paths (on Windows).

**Comment by zkovari** [comment]
Well, I have just finished the app recently, and I didn't have the opportunity so far to test it properly (especially on Windows). I will check this today, thank you.

**Comment by zkovari** [comment]
Fixed in [534e330](https://github.com/FTSRG/mondo-sam/commit/534e330dec7ff8942c62eae393106211811b40e9).

**Comment by itsdani** [comment]
Thanks!
