### ISSUE TITLE
Support reloading results from same file

### ISSUE THREAD

**Issue by itsdani** [FTSRG/mondo-sam#4]
In the current version, if the input file has changed content, it cannot be reloaded from the Shiny UI. However, renaming the file and using "Choose file" works.

It would be great if the file loader would reload the file even when the same path is given.

**Comment by zkovari** [comment]
Fixed in [afc42ea](https://github.com/FTSRG/mondo-sam/commit/afc42eaf4be33c12ac8f79ef424c02efcd2118b7).

**Comment by abelhegedus** [comment]
Thanks, verified.
