### ISSUE TITLE
Add source code to the built JAR files

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/mondo-sam#8]
Use the `maven-source-plugin` to add the source code to the built JAR files. 

It's sufficient to add this plugin to the parent POM. For an example, see the Train Benchmark: https://github.com/FTSRG/trainbenchmark/blob/master/pom.xml#L205

**Comment by zkovari** [comment]
Fixed.

**Comment by szarnyasg** [comment]
Thanks :+1:
